-- Martu OS V1 - additive domain model. Legacy columns and constraints remain
-- available so V0 and V1 code can be deployed independently and rolled back.

alter table public.clients
  add column if not exists logo_url text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists archived_at timestamptz;

alter table public.strategies
  add column if not exists notes text not null default '',
  add column if not exists change_summary text not null default '',
  add column if not exists valid_to timestamptz,
  add column if not exists supersedes_id bigint references public.strategies(id) on delete set null;

alter table public.ideas
  add column if not exists format text not null default 'Reel',
  add column if not exists captured_at timestamptz not null default now(),
  add column if not exists due_at timestamptz,
  add column if not exists notes text not null default '',
  add column if not exists archived_at timestamptz,
  add column if not exists deleted_at timestamptz;

alter table public.content_items
  add column if not exists cta text not null default '',
  add column if not exists notes text not null default '',
  add column if not exists archived_at timestamptz;

alter table public.tasks
  add column if not exists work_kind text not null default 'task',
  add column if not exists bucket text not null default 'next',
  add column if not exists starts_at timestamptz,
  add column if not exists waiting_until timestamptz,
  add column if not exists sort_order integer not null default 0,
  add column if not exists archived_at timestamptz;

alter table public.chat_threads
  add column if not exists archived_at timestamptz;

alter table public.memories
  add column if not exists memory_kind text not null default 'fact',
  add column if not exists lifecycle_status text not null default 'active',
  add column if not exists fingerprint text,
  add column if not exists confidence numeric(4,3) not null default 1,
  add column if not exists supersedes_id bigint references public.memories(id) on delete set null,
  add column if not exists forgotten_at timestamptz;

update public.memories
set fingerprint = lower(btrim(fact))
where fingerprint is null;

alter table public.ai_nudges
  add column if not exists lifecycle_state text not null default 'active',
  add column if not exists resolved_at timestamptz,
  add column if not exists dismissed_at timestamptz,
  add column if not exists snoozed_until timestamptz,
  add column if not exists resolution_reason text;

create table if not exists public.content_workflows (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  slug text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_workflows_client_slug_unique unique (client_id, slug),
  constraint content_workflows_name_not_blank check (btrim(name) <> ''),
  constraint content_workflows_slug_not_blank check (btrim(slug) <> '')
);

create unique index if not exists content_workflows_one_default_idx
  on public.content_workflows (client_id) where is_default;

create table if not exists public.content_workflow_states (
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.content_workflows(id) on delete cascade,
  slug text not null,
  label text not null,
  color text not null default '#64748b',
  position integer not null default 0,
  is_visible boolean not null default true,
  terminal_kind text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_workflow_states_workflow_slug_unique unique (workflow_id, slug),
  constraint content_workflow_states_label_not_blank check (btrim(label) <> ''),
  constraint content_workflow_states_terminal_valid check (terminal_kind is null or terminal_kind in ('delivered','published','cancelled'))
);

alter table public.content_items
  add column if not exists workflow_id bigint references public.content_workflows(id) on delete restrict,
  add column if not exists workflow_state_id bigint references public.content_workflow_states(id) on delete restrict;

insert into public.content_workflows (client_id, name, slug, is_default)
select c.id, 'Flujo principal', 'principal', true
from public.clients c
on conflict (client_id, slug) do nothing;

insert into public.content_workflow_states (workflow_id, slug, label, color, position, terminal_kind)
select w.id, seed.slug, seed.label, seed.color, seed.position, seed.terminal_kind
from public.content_workflows w
cross join (values
  ('idea', 'Idea', '#94a3b8', 10, null),
  ('script', 'Guion', '#8b5cf6', 20, null),
  ('to_record', 'Para grabar', '#f59e0b', 30, null),
  ('recorded', 'Grabado', '#f97316', 40, null),
  ('editing', 'Editando', '#0ea5e9', 50, null),
  ('ready', 'Listo', '#14b8a6', 60, null),
  ('approval', 'En aprobación', '#eab308', 70, null),
  ('approved', 'Aprobado', '#22c55e', 80, null),
  ('scheduled', 'Programado', '#3b82f6', 90, null),
  ('published', 'Publicado', '#16a34a', 100, 'published'),
  ('delivered', 'Entregado', '#475569', 110, 'delivered')
) as seed(slug, label, color, position, terminal_kind)
on conflict (workflow_id, slug) do nothing;

update public.content_items ci
set workflow_id = w.id,
    workflow_state_id = ws.id
from public.content_workflows w
join public.content_workflow_states ws on ws.workflow_id = w.id
where w.client_id = ci.client_id and w.is_default and ws.slug = ci.status
  and (ci.workflow_id is null or ci.workflow_state_id is null);

create table if not exists public.publications (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  content_item_id bigint not null references public.content_items(id) on delete cascade,
  platform text not null,
  status text not null default 'draft',
  external_id text,
  external_url text,
  scheduled_at timestamptz,
  published_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint publications_status_valid check (status in ('draft','scheduled','published','failed','archived')),
  constraint publications_platform_not_blank check (btrim(platform) <> ''),
  constraint publications_metadata_object check (jsonb_typeof(metadata) = 'object')
);

alter table public.content_metrics
  add column if not exists publication_id bigint references public.publications(id) on delete set null;

alter table public.ad_creatives
  add column if not exists content_item_id bigint references public.content_items(id) on delete set null;

create table if not exists public.insights (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  kind text not null,
  statement text not null,
  evidence jsonb not null default '{}'::jsonb,
  confidence numeric(4,3),
  content_item_id bigint references public.content_items(id) on delete set null,
  publication_id bigint references public.publications(id) on delete set null,
  campaign_id bigint references public.ad_campaigns(id) on delete set null,
  creative_id bigint references public.ad_creatives(id) on delete set null,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint insights_kind_valid check (kind in ('observation','pattern','hypothesis','recommendation')),
  constraint insights_statement_not_blank check (btrim(statement) <> ''),
  constraint insights_evidence_object check (jsonb_typeof(evidence) = 'object'),
  constraint insights_confidence_valid check (confidence is null or (confidence >= 0 and confidence <= 1))
);

alter table public.ideas
  add column if not exists source_insight_id bigint references public.insights(id) on delete set null;

create table if not exists public.script_versions (
  id bigint generated by default as identity primary key,
  script_id bigint not null references public.scripts(id) on delete cascade,
  version integer not null,
  title text not null,
  objective text not null default '',
  hook text not null default '',
  body text not null default '',
  cta text not null default '',
  notes text not null default '',
  actor text not null default 'Martu',
  created_at timestamptz not null default now(),
  constraint script_versions_script_version_unique unique (script_id, version),
  constraint script_versions_version_positive check (version > 0)
);

create table if not exists public.script_counters (
  client_id bigint primary key references public.clients(id) on delete cascade,
  next_number integer not null default 1,
  constraint script_counters_next_positive check (next_number > 0)
);

insert into public.script_counters (client_id, next_number)
select c.id, coalesce(max(s.script_number), 0) + 1
from public.clients c left join public.scripts s on s.client_id = c.id
group by c.id
on conflict (client_id) do update set next_number = greatest(public.script_counters.next_number, excluded.next_number);

create table if not exists public.idea_comments (
  id bigint generated by default as identity primary key,
  idea_id bigint not null references public.ideas(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint idea_comments_body_not_blank check (btrim(body) <> '')
);

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  title text not null,
  description text not null default '',
  kind text not null default 'event',
  starts_at timestamptz not null,
  ends_at timestamptz,
  all_day boolean not null default false,
  timezone text not null default 'America/Argentina/Buenos_Aires',
  status text not null default 'scheduled',
  source text not null default 'manual',
  external_provider text,
  external_id text,
  entity_type text,
  entity_id bigint,
  target_path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint calendar_events_title_not_blank check (btrim(title) <> ''),
  constraint calendar_events_range_valid check (ends_at is null or ends_at >= starts_at),
  constraint calendar_events_status_valid check (status in ('scheduled','completed','cancelled')),
  constraint calendar_events_metadata_object check (jsonb_typeof(metadata) = 'object'),
  constraint calendar_events_external_unique unique (external_provider, external_id)
);

create table if not exists public.open_loops (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  kind text not null default 'topic',
  title text not null,
  body text not null default '',
  status text not null default 'open',
  salience smallint not null default 3,
  next_eligible_at timestamptz,
  last_surfaced_at timestamptz,
  surface_count integer not null default 0,
  source_message_id bigint references public.chat_messages(id) on delete set null,
  linked_idea_id bigint references public.ideas(id) on delete set null,
  linked_task_id bigint references public.tasks(id) on delete set null,
  fingerprint text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint open_loops_kind_valid check (kind in ('idea','hypothesis','topic','later')),
  constraint open_loops_status_valid check (status in ('open','planned','resolved','archived')),
  constraint open_loops_salience_valid check (salience between 1 and 5),
  constraint open_loops_surface_nonnegative check (surface_count >= 0),
  constraint open_loops_title_not_blank check (btrim(title) <> '')
);

create table if not exists public.notification_suppressions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  kind text,
  scope text not null default 'kind',
  reason text not null default '',
  suppressed_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notification_suppressions_scope_valid check (scope in ('issue','kind','client','global'))
);

-- Critical ownership, queue and navigation indexes.
create index if not exists ideas_client_updated_v1_idx on public.ideas (client_id, updated_at desc) where deleted_at is null;
create index if not exists commitments_user_id_v1_idx on public.commitments (user_id);
create index if not exists reminders_user_id_v1_idx on public.reminders (user_id);
create index if not exists reminders_user_due_v1_idx on public.reminders (user_id, remind_at) where status in ('pending','snoozed');
create index if not exists ai_nudges_user_id_v1_idx on public.ai_nudges (user_id);
create index if not exists ai_nudges_center_v1_idx on public.ai_nudges (user_id, status, created_at desc);
create index if not exists ai_nudges_dedupe_history_v1_idx on public.ai_nudges (user_id, dedupe_key, created_at desc);
create index if not exists ai_nudges_recent_delivery_v1_idx on public.ai_nudges (user_id, delivered_at desc) where delivered_at is not null;
create index if not exists content_items_active_changed_v1_idx on public.content_items (client_id, status_changed_at) where archived_at is null;
create index if not exists content_items_workflow_state_v1_idx on public.content_items (workflow_state_id, pipeline_position);
create index if not exists content_workflow_states_order_v1_idx on public.content_workflow_states (workflow_id, position);
create index if not exists publications_content_v1_idx on public.publications (content_item_id, published_at desc);
create index if not exists publications_client_status_v1_idx on public.publications (client_id, status, scheduled_at);
create index if not exists content_metrics_publication_v1_idx on public.content_metrics (publication_id, captured_at desc) where publication_id is not null;
create index if not exists ad_creatives_content_v1_idx on public.ad_creatives (content_item_id) where content_item_id is not null;
create index if not exists insights_client_kind_v1_idx on public.insights (client_id, kind, created_at desc) where archived_at is null;
create index if not exists insights_content_v1_idx on public.insights (content_item_id) where content_item_id is not null;
create index if not exists script_versions_script_created_v1_idx on public.script_versions (script_id, created_at desc);
create index if not exists idea_comments_idea_created_v1_idx on public.idea_comments (idea_id, created_at);
create index if not exists calendar_events_user_starts_v1_idx on public.calendar_events (user_id, starts_at) where archived_at is null;
create index if not exists calendar_events_client_starts_v1_idx on public.calendar_events (client_id, starts_at) where client_id is not null and archived_at is null;
create index if not exists open_loops_due_v1_idx on public.open_loops (user_id, next_eligible_at, salience desc) where status = 'open';
create index if not exists open_loops_client_v1_idx on public.open_loops (client_id, updated_at desc) where client_id is not null and status = 'open';
create index if not exists memories_fingerprint_v1_idx on public.memories (user_id, client_id, memory_kind, fingerprint) where lifecycle_status = 'active';
create index if not exists notification_suppressions_lookup_v1_idx on public.notification_suppressions (user_id, client_id, kind, suppressed_until);
create index if not exists chat_threads_recent_v1_idx on public.chat_threads (user_id, archived_at, last_message_at desc);
create index if not exists strategies_supersedes_v1_idx on public.strategies (supersedes_id) where supersedes_id is not null;
create index if not exists ideas_source_insight_v1_idx on public.ideas (source_insight_id) where source_insight_id is not null;
create index if not exists content_items_workflow_v1_idx on public.content_items (workflow_id) where workflow_id is not null;
create index if not exists memories_supersedes_v1_idx on public.memories (supersedes_id) where supersedes_id is not null;
create index if not exists insights_user_v1_idx on public.insights (user_id);
create index if not exists insights_publication_v1_idx on public.insights (publication_id) where publication_id is not null;
create index if not exists insights_campaign_v1_idx on public.insights (campaign_id) where campaign_id is not null;
create index if not exists insights_creative_v1_idx on public.insights (creative_id) where creative_id is not null;
create index if not exists idea_comments_user_v1_idx on public.idea_comments (user_id);
create index if not exists open_loops_source_message_v1_idx on public.open_loops (source_message_id) where source_message_id is not null;
create index if not exists open_loops_linked_idea_v1_idx on public.open_loops (linked_idea_id) where linked_idea_id is not null;
create index if not exists open_loops_linked_task_v1_idx on public.open_loops (linked_task_id) where linked_task_id is not null;

-- Keep updated_at database-owned for all new mutable entities.
drop trigger if exists content_workflows_set_updated_at on public.content_workflows;
create trigger content_workflows_set_updated_at before update on public.content_workflows for each row execute function public.set_updated_at();
drop trigger if exists content_workflow_states_set_updated_at on public.content_workflow_states;
create trigger content_workflow_states_set_updated_at before update on public.content_workflow_states for each row execute function public.set_updated_at();
drop trigger if exists publications_set_updated_at on public.publications;
create trigger publications_set_updated_at before update on public.publications for each row execute function public.set_updated_at();
drop trigger if exists insights_set_updated_at on public.insights;
create trigger insights_set_updated_at before update on public.insights for each row execute function public.set_updated_at();
drop trigger if exists idea_comments_set_updated_at on public.idea_comments;
create trigger idea_comments_set_updated_at before update on public.idea_comments for each row execute function public.set_updated_at();
drop trigger if exists calendar_events_set_updated_at on public.calendar_events;
create trigger calendar_events_set_updated_at before update on public.calendar_events for each row execute function public.set_updated_at();
drop trigger if exists open_loops_set_updated_at on public.open_loops;
create trigger open_loops_set_updated_at before update on public.open_loops for each row execute function public.set_updated_at();
drop trigger if exists notification_suppressions_set_updated_at on public.notification_suppressions;
create trigger notification_suppressions_set_updated_at before update on public.notification_suppressions for each row execute function public.set_updated_at();

alter table public.content_workflows enable row level security;
alter table public.content_workflow_states enable row level security;
alter table public.publications enable row level security;
alter table public.insights enable row level security;
alter table public.script_versions enable row level security;
alter table public.script_counters enable row level security;
alter table public.idea_comments enable row level security;
alter table public.calendar_events enable row level security;
alter table public.open_loops enable row level security;
alter table public.notification_suppressions enable row level security;
