-- Martu OS V0 - canonical relational model.
-- PostgreSQL/Supabase is the only production source of truth. This migration is
-- intentionally compatible with PGlite so local development exercises the same SQL.

create table if not exists public.schema_migrations (
  version text primary key,
  applied_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  email text,
  timezone text not null default 'America/Argentina/Buenos_Aires',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_slug_not_blank check (btrim(slug) <> ''),
  constraint users_name_not_blank check (btrim(name) <> '')
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  slug text not null,
  name text not null,
  description text not null default '',
  summary text not null default '',
  status text not null default 'active',
  accent text not null default '#496a50',
  avatar_initial text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clients_user_slug_unique unique (user_id, slug),
  constraint clients_status_valid check (status in ('active', 'paused', 'archived')),
  constraint clients_slug_not_blank check (btrim(slug) <> ''),
  constraint clients_name_not_blank check (btrim(name) <> '')
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  short_name text not null,
  tab_key text,
  sort_order integer not null default 0,
  is_custom boolean not null default false,
  created_at timestamptz not null default now(),
  constraint services_slug_not_blank check (btrim(slug) <> ''),
  constraint services_name_not_blank check (btrim(name) <> '')
);

create table if not exists public.client_services (
  client_id bigint not null references public.clients(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete restrict,
  is_active boolean not null default true,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (client_id, service_id),
  constraint client_services_settings_object check (jsonb_typeof(settings) = 'object')
);

create table if not exists public.briefs (
  id bigint generated by default as identity primary key,
  client_id bigint not null unique references public.clients(id) on delete cascade,
  status text not null default 'draft',
  objectives text[] not null default '{}',
  audience text not null default '',
  tone text not null default '',
  positioning text not null default '',
  differentiators text[] not null default '{}',
  constraints text[] not null default '{}',
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint briefs_status_valid check (status in ('missing', 'draft', 'complete'))
);

create table if not exists public.strategies (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  title text not null,
  status text not null default 'draft',
  version integer not null default 1,
  objectives text[] not null default '{}',
  audience text not null default '',
  tone text not null default '',
  positioning text not null default '',
  pillars text[] not null default '{}',
  hypotheses text[] not null default '{}',
  decisions text[] not null default '{}',
  valid_from timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint strategies_client_version_unique unique (client_id, version),
  constraint strategies_status_valid check (status in ('draft', 'active', 'archived')),
  constraint strategies_version_positive check (version > 0)
);

create table if not exists public.ideas (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  seed_key text,
  title text not null,
  description text not null default '',
  origin text not null default 'manual',
  status text not null default 'new',
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ideas_client_seed_key_unique unique (client_id, seed_key),
  constraint ideas_status_valid check (status in ('new', 'selected', 'developing', 'produced', 'discarded')),
  constraint ideas_title_not_blank check (btrim(title) <> '')
);

create table if not exists public.scripts (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  idea_id bigint references public.ideas(id) on delete set null,
  seed_key text,
  script_number integer,
  title text not null,
  format text not null default 'Reel',
  objective text not null default '',
  hook text not null default '',
  body text not null default '',
  cta text not null default '',
  status text not null default 'draft',
  notes text not null default '',
  version integer not null default 1,
  due_at timestamptz,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint scripts_client_seed_key_unique unique (client_id, seed_key),
  constraint scripts_client_number_unique unique (client_id, script_number),
  constraint scripts_status_valid check (status in ('draft', 'review', 'approved', 'archived')),
  constraint scripts_version_positive check (version > 0),
  constraint scripts_number_positive check (script_number is null or script_number > 0),
  constraint scripts_title_not_blank check (btrim(title) <> '')
);

create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  idea_id bigint references public.ideas(id) on delete set null,
  script_id bigint references public.scripts(id) on delete set null,
  seed_key text,
  title text not null,
  format text not null default 'Reel',
  channel text not null default 'Instagram',
  status text not null default 'idea',
  pipeline_position integer not null default 0,
  caption text not null default '',
  assignee text not null default 'Martu',
  due_at timestamptz,
  scheduled_at timestamptz,
  published_at timestamptz,
  delivered_at timestamptz,
  status_changed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_items_client_seed_key_unique unique (client_id, seed_key),
  constraint content_items_status_valid check (status in (
    'idea', 'script', 'to_record', 'recorded', 'editing', 'ready',
    'approval', 'approved', 'scheduled', 'published', 'delivered'
  )),
  constraint content_items_title_not_blank check (btrim(title) <> '')
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  seed_key text,
  title text not null,
  description text not null default '',
  status text not null default 'pending',
  priority text not null default 'medium',
  due_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  snoozed_until timestamptz,
  source text not null default 'manual',
  entity_type text,
  entity_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tasks_user_seed_key_unique unique (user_id, seed_key),
  constraint tasks_status_valid check (status in ('pending', 'in_progress', 'blocked', 'completed', 'cancelled')),
  constraint tasks_priority_valid check (priority in ('low', 'medium', 'high', 'urgent')),
  constraint tasks_title_not_blank check (btrim(title) <> '')
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  seed_key text,
  text text not null,
  tags text[] not null default '{}',
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notes_client_seed_key_unique unique (client_id, seed_key),
  constraint notes_text_not_blank check (btrim(text) <> '')
);

create table if not exists public.meetings (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  seed_key text,
  title text not null,
  starts_at timestamptz not null,
  duration_minutes integer not null default 30,
  summary text not null default '',
  decisions text[] not null default '{}',
  next_steps text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint meetings_client_seed_key_unique unique (client_id, seed_key),
  constraint meetings_duration_positive check (duration_minutes > 0)
);

create table if not exists public.file_links (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  seed_key text,
  name text not null,
  kind text not null default 'document',
  url text not null,
  provider text not null default 'demo',
  size_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint file_links_client_seed_key_unique unique (client_id, seed_key),
  constraint file_links_url_not_blank check (btrim(url) <> '')
);

create table if not exists public.metric_snapshots (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  seed_key text,
  period_start date not null,
  period_end date not null,
  followers integer,
  reach integer not null default 0,
  views integer not null default 0,
  saves integer not null default 0,
  shares integer not null default 0,
  comments integer not null default 0,
  clicks integer not null default 0,
  inquiries integer not null default 0,
  conversions integer not null default 0,
  source text not null default 'demo',
  created_at timestamptz not null default now(),
  constraint metric_snapshots_client_seed_key_unique unique (client_id, seed_key),
  constraint metric_snapshots_period_valid check (period_end >= period_start)
);

create table if not exists public.content_metrics (
  id bigint generated by default as identity primary key,
  content_item_id bigint not null references public.content_items(id) on delete cascade,
  captured_at timestamptz not null,
  reach integer not null default 0,
  views integer not null default 0,
  avg_watch_seconds numeric(8,2),
  retention_rate numeric(6,5),
  saves integer not null default 0,
  shares integer not null default 0,
  comments integer not null default 0,
  clicks integer not null default 0,
  inquiries integer not null default 0,
  conversions integer not null default 0,
  source text not null default 'demo',
  created_at timestamptz not null default now(),
  constraint content_metrics_content_captured_unique unique (content_item_id, captured_at),
  constraint content_metrics_retention_valid check (retention_rate is null or (retention_rate >= 0 and retention_rate <= 1))
);

create table if not exists public.ad_campaigns (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  seed_key text,
  name text not null,
  objective text not null,
  status text not null default 'draft',
  starts_at timestamptz,
  ends_at timestamptz,
  spend numeric(12,2) not null default 0,
  impressions integer not null default 0,
  clicks integer not null default 0,
  ctr numeric(8,5),
  cpc numeric(12,2),
  cpa numeric(12,2),
  roas numeric(10,3),
  observations text not null default '',
  source text not null default 'demo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ad_campaigns_client_seed_key_unique unique (client_id, seed_key),
  constraint ad_campaigns_status_valid check (status in ('draft', 'active', 'paused', 'completed')),
  constraint ad_campaigns_spend_nonnegative check (spend >= 0)
);

create table if not exists public.ad_creatives (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.ad_campaigns(id) on delete cascade,
  seed_key text,
  name text not null,
  format text not null default 'video',
  status text not null default 'active',
  hook text not null default '',
  spend numeric(12,2) not null default 0,
  impressions integer not null default 0,
  clicks integer not null default 0,
  ctr numeric(8,5),
  cpc numeric(12,2),
  conversions integer not null default 0,
  observations text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ad_creatives_campaign_seed_key_unique unique (campaign_id, seed_key),
  constraint ad_creatives_status_valid check (status in ('draft', 'active', 'paused', 'archived'))
);

create table if not exists public.chat_threads (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  scope text not null default 'global',
  title text not null default 'Supervisor IA',
  source text not null default 'web',
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chat_threads_scope_valid check (scope in ('global', 'client')),
  constraint chat_threads_scope_client_consistent check (
    (scope = 'global' and client_id is null) or (scope = 'client' and client_id is not null)
  )
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.chat_threads(id) on delete cascade,
  role text not null,
  content text not null,
  mode text not null default 'supervisor',
  tool_name text,
  tool_payload jsonb,
  action_result jsonb,
  created_at timestamptz not null default now(),
  constraint chat_messages_role_valid check (role in ('user', 'assistant', 'system', 'tool')),
  constraint chat_messages_mode_valid check (mode in ('supervisor', 'strategist', 'creative', 'analyst')),
  constraint chat_messages_content_not_blank check (btrim(content) <> '')
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  scope text not null default 'global',
  category text not null,
  fact text not null,
  importance smallint not null default 3,
  source text not null default 'manual',
  source_message_id bigint references public.chat_messages(id) on delete set null,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint memories_scope_valid check (scope in ('global', 'client')),
  constraint memories_scope_client_consistent check (
    (scope = 'global' and client_id is null) or (scope = 'client' and client_id is not null)
  ),
  constraint memories_importance_valid check (importance between 1 and 5),
  constraint memories_fact_not_blank check (btrim(fact) <> '')
);

create table if not exists public.communication_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  language text not null default 'es-AR',
  formality smallint not null default 2,
  preferred_length text not null default 'short',
  humor smallint not null default 3,
  insistence_level smallint not null default 3,
  quiet_hours_start time not null default '22:30',
  quiet_hours_end time not null default '08:30',
  morning_briefing_at time not null default '09:00',
  midday_check_at time not null default '13:30',
  end_of_day_at time,
  expressions text[] not null default array['che', 'dale'],
  minor_task_lead_hours integer not null default 24,
  explicit_preferences text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint communication_profiles_formality_valid check (formality between 1 and 5),
  constraint communication_profiles_humor_valid check (humor between 1 and 5),
  constraint communication_profiles_insistence_valid check (insistence_level between 1 and 5),
  constraint communication_profiles_length_valid check (preferred_length in ('short', 'medium', 'long')),
  constraint communication_profiles_lead_nonnegative check (minor_task_lead_hours >= 0)
);

create table if not exists public.commitments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete set null,
  script_id bigint references public.scripts(id) on delete set null,
  content_item_id bigint references public.content_items(id) on delete set null,
  meeting_id bigint references public.meetings(id) on delete set null,
  source_message_id bigint references public.chat_messages(id) on delete set null,
  seed_key text,
  title text not null,
  intention text not null,
  status text not null default 'open',
  due_at timestamptz not null,
  source text not null default 'chat',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commitments_user_seed_key_unique unique (user_id, seed_key),
  constraint commitments_status_valid check (status in ('open', 'done', 'rescheduled', 'cancelled')),
  constraint commitments_title_not_blank check (btrim(title) <> '')
);

create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  commitment_id bigint references public.commitments(id) on delete cascade,
  seed_key text,
  title text not null,
  status text not null default 'pending',
  remind_at timestamptz not null,
  next_followup_at timestamptz,
  recurrence text,
  channel text not null default 'web_push',
  target_path text not null default '/',
  cooldown_key text,
  last_triggered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reminders_user_seed_key_unique unique (user_id, seed_key),
  constraint reminders_status_valid check (status in ('pending', 'sent', 'snoozed', 'done', 'cancelled')),
  constraint reminders_channel_valid check (channel in ('web_push', 'in_app', 'whatsapp')),
  constraint reminders_title_not_blank check (btrim(title) <> '')
);

create table if not exists public.ai_nudges (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete set null,
  commitment_id bigint references public.commitments(id) on delete set null,
  reminder_id bigint references public.reminders(id) on delete set null,
  kind text not null,
  severity text not null default 'medium',
  title text not null,
  message text not null,
  status text not null default 'pending',
  dedupe_key text not null,
  deliver_after timestamptz not null default now(),
  cooldown_until timestamptz,
  delivered_at timestamptz,
  seen_at timestamptz,
  acted_at timestamptz,
  target_path text not null default '/',
  quick_actions jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_nudges_status_valid check (status in ('pending', 'delivered', 'seen', 'acted', 'dismissed', 'expired')),
  constraint ai_nudges_severity_valid check (severity in ('low', 'medium', 'high', 'urgent')),
  constraint ai_nudges_quick_actions_array check (jsonb_typeof(quick_actions) = 'array'),
  constraint ai_nudges_metadata_object check (jsonb_typeof(metadata) = 'object'),
  constraint ai_nudges_dedupe_not_blank check (btrim(dedupe_key) <> '')
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  status text not null default 'active',
  last_used_at timestamptz,
  failure_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint push_subscriptions_status_valid check (status in ('active', 'expired', 'revoked')),
  constraint push_subscriptions_failure_nonnegative check (failure_count >= 0)
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  client_id bigint references public.clients(id) on delete cascade,
  actor text not null default 'Martu',
  type text not null,
  title text not null,
  description text not null default '',
  entity_type text,
  entity_id bigint,
  target_path text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint activity_events_metadata_object check (jsonb_typeof(metadata) = 'object')
);

-- Foreign-key indexes (PostgreSQL does not create these automatically).
create index if not exists clients_user_id_idx on public.clients (user_id);
create index if not exists client_services_service_id_idx on public.client_services (service_id);
create index if not exists strategies_client_id_idx on public.strategies (client_id);
create index if not exists ideas_client_created_idx on public.ideas (client_id, created_at desc);
create index if not exists scripts_client_updated_idx on public.scripts (client_id, updated_at desc);
create index if not exists scripts_idea_id_idx on public.scripts (idea_id) where idea_id is not null;
create index if not exists content_items_client_updated_idx on public.content_items (client_id, updated_at desc);
create index if not exists content_items_idea_id_idx on public.content_items (idea_id) where idea_id is not null;
create index if not exists content_items_script_id_idx on public.content_items (script_id) where script_id is not null;
create index if not exists tasks_user_id_idx on public.tasks (user_id);
create index if not exists tasks_client_id_idx on public.tasks (client_id) where client_id is not null;
create index if not exists notes_user_id_idx on public.notes (user_id);
create index if not exists notes_client_created_idx on public.notes (client_id, created_at desc);
create index if not exists meetings_client_starts_idx on public.meetings (client_id, starts_at desc);
create index if not exists file_links_client_created_idx on public.file_links (client_id, created_at desc);
create index if not exists metric_snapshots_client_period_idx on public.metric_snapshots (client_id, period_end desc);
create index if not exists content_metrics_content_captured_idx on public.content_metrics (content_item_id, captured_at desc);
create index if not exists ad_campaigns_client_updated_idx on public.ad_campaigns (client_id, updated_at desc);
create index if not exists ad_creatives_campaign_id_idx on public.ad_creatives (campaign_id);
create index if not exists chat_threads_user_updated_idx on public.chat_threads (user_id, updated_at desc);
create index if not exists chat_threads_client_id_idx on public.chat_threads (client_id) where client_id is not null;
create index if not exists chat_messages_thread_created_idx on public.chat_messages (thread_id, created_at);
create index if not exists memories_user_scope_idx on public.memories (user_id, scope, importance desc);
create index if not exists memories_client_id_idx on public.memories (client_id) where client_id is not null;
create index if not exists memories_source_message_id_idx on public.memories (source_message_id) where source_message_id is not null;
create index if not exists commitments_client_id_idx on public.commitments (client_id) where client_id is not null;
create index if not exists commitments_task_id_idx on public.commitments (task_id) where task_id is not null;
create index if not exists commitments_script_id_idx on public.commitments (script_id) where script_id is not null;
create index if not exists commitments_content_item_id_idx on public.commitments (content_item_id) where content_item_id is not null;
create index if not exists commitments_meeting_id_idx on public.commitments (meeting_id) where meeting_id is not null;
create index if not exists commitments_source_message_id_idx on public.commitments (source_message_id) where source_message_id is not null;
create index if not exists reminders_client_id_idx on public.reminders (client_id) where client_id is not null;
create index if not exists reminders_task_id_idx on public.reminders (task_id) where task_id is not null;
create index if not exists reminders_commitment_id_idx on public.reminders (commitment_id) where commitment_id is not null;
create index if not exists ai_nudges_client_id_idx on public.ai_nudges (client_id) where client_id is not null;
create index if not exists ai_nudges_task_id_idx on public.ai_nudges (task_id) where task_id is not null;
create index if not exists ai_nudges_commitment_id_idx on public.ai_nudges (commitment_id) where commitment_id is not null;
create index if not exists ai_nudges_reminder_id_idx on public.ai_nudges (reminder_id) where reminder_id is not null;
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions (user_id);
create index if not exists activity_events_user_occurred_idx on public.activity_events (user_id, occurred_at desc);
create index if not exists activity_events_client_occurred_idx on public.activity_events (client_id, occurred_at desc) where client_id is not null;

-- Hot-path partial/composite indexes used by Mi Dia and the scheduler.
create index if not exists tasks_open_due_idx
  on public.tasks (user_id, due_at, priority)
  where status in ('pending', 'in_progress', 'blocked');
create index if not exists content_items_active_due_idx
  on public.content_items (client_id, due_at, status)
  where status not in ('published', 'delivered');
create index if not exists commitments_open_due_idx
  on public.commitments (user_id, due_at)
  where status = 'open';
create index if not exists reminders_pending_due_idx
  on public.reminders (remind_at, user_id)
  where status in ('pending', 'snoozed');
create index if not exists ai_nudges_delivery_queue_idx
  on public.ai_nudges (deliver_after, severity)
  where status = 'pending';
create unique index if not exists ai_nudges_active_dedupe_idx
  on public.ai_nudges (user_id, dedupe_key)
  where status in ('pending', 'delivered', 'seen');
create index if not exists push_subscriptions_active_idx
  on public.push_subscriptions (user_id, updated_at desc)
  where status = 'active';

-- updated_at is always database-owned so every writer behaves consistently.
drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at before update on public.clients for each row execute function public.set_updated_at();
drop trigger if exists briefs_set_updated_at on public.briefs;
create trigger briefs_set_updated_at before update on public.briefs for each row execute function public.set_updated_at();
drop trigger if exists strategies_set_updated_at on public.strategies;
create trigger strategies_set_updated_at before update on public.strategies for each row execute function public.set_updated_at();
drop trigger if exists ideas_set_updated_at on public.ideas;
create trigger ideas_set_updated_at before update on public.ideas for each row execute function public.set_updated_at();
drop trigger if exists scripts_set_updated_at on public.scripts;
create trigger scripts_set_updated_at before update on public.scripts for each row execute function public.set_updated_at();
drop trigger if exists content_items_set_updated_at on public.content_items;
create trigger content_items_set_updated_at before update on public.content_items for each row execute function public.set_updated_at();
drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks for each row execute function public.set_updated_at();
drop trigger if exists notes_set_updated_at on public.notes;
create trigger notes_set_updated_at before update on public.notes for each row execute function public.set_updated_at();
drop trigger if exists meetings_set_updated_at on public.meetings;
create trigger meetings_set_updated_at before update on public.meetings for each row execute function public.set_updated_at();
drop trigger if exists file_links_set_updated_at on public.file_links;
create trigger file_links_set_updated_at before update on public.file_links for each row execute function public.set_updated_at();
drop trigger if exists ad_campaigns_set_updated_at on public.ad_campaigns;
create trigger ad_campaigns_set_updated_at before update on public.ad_campaigns for each row execute function public.set_updated_at();
drop trigger if exists ad_creatives_set_updated_at on public.ad_creatives;
create trigger ad_creatives_set_updated_at before update on public.ad_creatives for each row execute function public.set_updated_at();
drop trigger if exists chat_threads_set_updated_at on public.chat_threads;
create trigger chat_threads_set_updated_at before update on public.chat_threads for each row execute function public.set_updated_at();
drop trigger if exists memories_set_updated_at on public.memories;
create trigger memories_set_updated_at before update on public.memories for each row execute function public.set_updated_at();
drop trigger if exists communication_profiles_set_updated_at on public.communication_profiles;
create trigger communication_profiles_set_updated_at before update on public.communication_profiles for each row execute function public.set_updated_at();
drop trigger if exists commitments_set_updated_at on public.commitments;
create trigger commitments_set_updated_at before update on public.commitments for each row execute function public.set_updated_at();
drop trigger if exists reminders_set_updated_at on public.reminders;
create trigger reminders_set_updated_at before update on public.reminders for each row execute function public.set_updated_at();
drop trigger if exists ai_nudges_set_updated_at on public.ai_nudges;
create trigger ai_nudges_set_updated_at before update on public.ai_nudges for each row execute function public.set_updated_at();
drop trigger if exists push_subscriptions_set_updated_at on public.push_subscriptions;
create trigger push_subscriptions_set_updated_at before update on public.push_subscriptions for each row execute function public.set_updated_at();

-- The browser never talks to these tables directly in V0. RLS with no public
-- policy prevents accidental exposure through Supabase's Data API; the Vercel
-- backend connects through DATABASE_URL and owns authorization.
alter table public.users enable row level security;
alter table public.clients enable row level security;
alter table public.services enable row level security;
alter table public.client_services enable row level security;
alter table public.briefs enable row level security;
alter table public.strategies enable row level security;
alter table public.ideas enable row level security;
alter table public.scripts enable row level security;
alter table public.content_items enable row level security;
alter table public.tasks enable row level security;
alter table public.notes enable row level security;
alter table public.meetings enable row level security;
alter table public.file_links enable row level security;
alter table public.metric_snapshots enable row level security;
alter table public.content_metrics enable row level security;
alter table public.ad_campaigns enable row level security;
alter table public.ad_creatives enable row level security;
alter table public.chat_threads enable row level security;
alter table public.chat_messages enable row level security;
alter table public.memories enable row level security;
alter table public.communication_profiles enable row level security;
alter table public.commitments enable row level security;
alter table public.reminders enable row level security;
alter table public.ai_nudges enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.activity_events enable row level security;
