-- Instagram API with Instagram Login V0.1.
-- Tokens remain server-side and are stored as versioned AES-GCM envelopes.

create table if not exists public.instagram_connections (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  instagram_account_id text not null,
  username text not null,
  account_type text,
  profile_picture_url text,
  encrypted_access_token text not null,
  expires_at timestamptz,
  scopes text[] not null default '{}',
  status text not null default 'connected',
  connected_at timestamptz not null default now(),
  last_sync_at timestamptz,
  sync_started_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instagram_connections_client_unique unique (client_id),
  constraint instagram_connections_status_valid check (status in ('connected', 'syncing', 'needs_reauth', 'disconnected', 'error')),
  constraint instagram_connections_username_not_blank check (btrim(username) <> ''),
  constraint instagram_connections_account_not_blank check (btrim(instagram_account_id) <> '')
);

create table if not exists public.instagram_media (
  id bigint generated by default as identity primary key,
  connection_id bigint not null references public.instagram_connections(id) on delete cascade,
  content_item_id bigint references public.content_items(id) on delete set null,
  instagram_media_id text not null,
  media_type text not null,
  media_product_type text,
  caption text,
  permalink text,
  media_url text,
  thumbnail_url text,
  published_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  first_synced_at timestamptz not null default now(),
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instagram_media_external_unique unique (connection_id, instagram_media_id),
  constraint instagram_media_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create table if not exists public.instagram_media_insights (
  id bigint generated by default as identity primary key,
  media_id bigint not null references public.instagram_media(id) on delete cascade,
  metric_name text not null,
  metric_value jsonb not null,
  period text not null default 'lifetime',
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint instagram_media_insights_unique unique (media_id, metric_name, period),
  constraint instagram_media_insights_name_not_blank check (btrim(metric_name) <> '')
);

create table if not exists public.instagram_account_insights (
  id bigint generated by default as identity primary key,
  connection_id bigint not null references public.instagram_connections(id) on delete cascade,
  metric_name text not null,
  metric_value jsonb not null,
  period text not null,
  end_time timestamptz,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists instagram_account_insights_unique_idx
  on public.instagram_account_insights (connection_id, metric_name, period, coalesce(end_time, '-infinity'::timestamptz));
create index if not exists instagram_connections_client_id_idx on public.instagram_connections (client_id);
create index if not exists instagram_media_connection_published_idx on public.instagram_media (connection_id, published_at desc);
create index if not exists instagram_media_content_item_id_idx on public.instagram_media (content_item_id) where content_item_id is not null;
create index if not exists instagram_media_insights_media_id_idx on public.instagram_media_insights (media_id);
create index if not exists instagram_account_insights_connection_id_idx on public.instagram_account_insights (connection_id, fetched_at desc);

drop trigger if exists instagram_connections_set_updated_at on public.instagram_connections;
create trigger instagram_connections_set_updated_at before update on public.instagram_connections for each row execute function public.set_updated_at();
drop trigger if exists instagram_media_set_updated_at on public.instagram_media;
create trigger instagram_media_set_updated_at before update on public.instagram_media for each row execute function public.set_updated_at();
drop trigger if exists instagram_media_insights_set_updated_at on public.instagram_media_insights;
create trigger instagram_media_insights_set_updated_at before update on public.instagram_media_insights for each row execute function public.set_updated_at();
drop trigger if exists instagram_account_insights_set_updated_at on public.instagram_account_insights;
create trigger instagram_account_insights_set_updated_at before update on public.instagram_account_insights for each row execute function public.set_updated_at();

alter table public.instagram_connections enable row level security;
alter table public.instagram_media enable row level security;
alter table public.instagram_media_insights enable row level security;
alter table public.instagram_account_insights enable row level security;
